Add tests, change writeFile to write string
balena-io-modules/blinking pull request #7
Opened 2022-07-11 21:07 UTC by cywang117

Previous:
```
writeFileAsync(ledFile, 1);
```
This was causing typing issues in the Supervisor repo tests.

Now:
```
writeFileAsync(ledFile, '1');
```

Also took the opportunity to write tests for this module, so that we don't need to test its functionality in the balena Supervisor codebase. The large positive line count is mainly due to the addition of `package-lock.json`.

Change-type: patch
Signed-off-by: Christina Wang <christina@balena.io>

2022-07-11 21:28 UTC, cywang117 commented
Related: https://github.com/balena-io-modules/blinking/pull/6

2022-07-12 16:24 UTC, pipex commented on index.ts
> +const numToArray = (n: number): undefined[] => new Array(n).fill(undefined);
```suggestion
const arrayOf = (length: number): undefined[] => new Array(length).fill(undefined);
```

You can also do 
```
const arrayOf = (length: number) => Array.from(Array(length))
```

2022-07-12 16:25 UTC, pipex commented on index.ts
> +const writeFileAsync = Bluebird.promisify(writeFile);
Why not use `fs.promises.writeFile`?

2022-07-12 16:26 UTC, pipex commented on index.ts
> +const writeFileAsync = Bluebird.promisify(writeFile);
is it because of the cancellation?

2022-07-12 16:27 UTC, pipex commented on index.ts
> +const writeFileAsync = Bluebird.promisify(writeFile);
If that's the case I would maybe do 

```
 import { writeFileSync } from 'fs';
```

And then the promisified function is called `writeFile`

2022-07-12 16:39 UTC, pipex commented on test/index.spec.ts
> +    const expectOff = async () => await expectValue(LED_FILE_PATH, '0');
The `On` `Off` suffixes are usually associated with events (at least for me), maybe we can be a bit more explicit for better readability? Something like

```suggestion
    const expectLedTurnOn = async () => await expectValue(LED_FILE_PATH, '1');
    const expectLedTurnOff = async () => await expectValue(LED_FILE_PATH, '0');
```

2022-07-12 16:43 UTC, pipex commented on tsconfig.json
> +        "types": ["node"],
Will this allow us to remove the custom type under `typings/blinking.d.ts` on the supervisor?

2022-07-12 18:04 UTC, cywang117 commented on package.json
> +    "lint": "balena-lint --typescript -t tsconfig.json --fix index.ts",
This is the [recommended](See: https://github.com/balena-io-modules/node-balena-lint#rules-that-require-type-information) argument to add to silence the following when running `lint`:
```
Warning: The 'no-floating-promises' rule requires type information.
```

2022-07-12 18:08 UTC, cywang117 commented on index.ts
> +const numToArray = (n: number): undefined[] => new Array(n).fill(undefined);
🧠

2022-07-12 18:12 UTC, cywang117 commented on test/index.spec.ts
> +    const expectOff = async () => await expectValue(LED_FILE_PATH, '0');
Sure!

2022-07-12 18:18 UTC, cywang117 commented on tsconfig.json
> +        "types": ["node"],
I don't think we've needed blinking.d.ts in the Supervisor, ever since blinking was changed to TypeScript in v0.0.4.

2022-07-12 18:21 UTC, cywang117 commented on tsconfig.json
> +        "types": ["node"],
I added types: node to tsconfig.json because the writeFile import was erroring in my IDE.

2022-07-12 18:27 UTC, cywang117 commented on test/index.spec.ts
> +    const expectOff = async () => await expectValue(LED_FILE_PATH, '0');
Changed in https://github.com/balena-io-modules/blinking/commit/d15e090f8d0af06c973e558eed32a2854fd70f06

2022-07-12 18:27 UTC, cywang117 commented on index.ts
> +const writeFileAsync = Bluebird.promisify(writeFile);
Changed in https://github.com/balena-io-modules/blinking/commit/d15e090f8d0af06c973e558eed32a2854fd70f06

2022-07-12 18:27 UTC, cywang117 commented on index.ts
> +const numToArray = (n: number): undefined[] => new Array(n).fill(undefined);
Using this in https://github.com/balena-io-modules/blinking/commit/d15e090f8d0af06c973e558eed32a2854fd70f06

2022-07-13 21:14 UTC, cywang117 commented
@balena-ci retest

2022-07-14 21:02 UTC, cywang117 commented
Tests don't pass consistently, due to the way Promises are handled in the current implementation. I'll be looking at this more but will put it in draft for now

2022-07-19 13:09 UTC, Page- requested changes

2022-07-19 13:09 UTC, Page- commented on index.ts
> +const writeFile = Bluebird.promisify(writeFileSync);
This needs to remain using the `writeFile` version as the sync one is, well, synchronous. If you're going to use the sync version you'd be better off not using promises at all (but it'd overall be a very bad idea)
```suggestion
const writeFileAsync = Bluebird.promisify(writeFile);
```

2022-07-19 13:11 UTC, Page- commented on package.json
> +    "@types/bluebird": "^3.5.36",
This should stay as a normal dependency - the types for normal dependencies should also be normal dependencies because downstream users of this module that use typescript will also need to install the matching typings or things will break

2024-08-02 15:45 UTC, pipex commented
Superseded by #17

2024-08-02 15:45 UTC, closed without merging